spring:
  application:
    name: eureka2
  profiles:
    active: server2
server:
  port: 8762
eureka:
  eureka:
  #自我保护模式，如果过多的服务因为网络原因丢失则启动保护模式,不再注销任何微服务，当网络故障回复后，该节点会自动退出自我保护模式
  server:
    enable-self-preservation: true
  instance:
    hostname: server2
  client:
    #registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server1:8761/eureka/,http://server3:8763/eureka/