spring:
  application:
    name: eureka1
  profiles:
    active: server1
server:
  port: 8761
eureka:
   #自我保护模式，如果过多的服务因为网络原因丢失则启动保护模式,不再注销任何微服务，当网络故障回复后，
   #该节点会自动退出自我保护模式,如果在15分钟内超过85%的节点都没有正常的心跳，那么Eureka就认为客户端与注册中心出现了网络故障
  server:
    enable-self-preservation: true
  instance:
    hostname: server1
  client:
    #registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server2:8762/eureka/,http://server3:8763/eureka/