spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhangYu1016/configServer.git
          username: 1040601138@qq.com
          password: yu159456
          basedir: C:\computer\java\Git\configRepsitory
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8861